version: "3" # version of docker compose

services:
  portfolio:
    build:
      context: ..
      dockerfile: docker_files/Dockerfile
    image: portfolio-image:latest
    container_name: portfolio-container
    hostname: portfolio
    restart: "no"
    ports:
      - "8080:80"
