apiVersion: v1
kind: Service
metadata:
  name: frontend-service-cluster-ip
  namespace: fibonacci
spec:
  type: ClusterIP
  selector:
    fibonacci: frontend
  ports:
    - port: 3000
      targetPort: 3000
