version: "3" # Version of docker-compose

services:
  redis-server:
    build: ./redis_server
    image: redis-server-image:latest
    container_name: redis-server-container
    hostname: redis-server
    restart: "no"
    ports:
      - "6380:6379"

  app:
    build: ./app
    image: app-image:latest
    container_name: app-container
    hostname: app
    restart: "no"
    environment:
      - APP_PORT=3000

      - REDIS_SERVER_HOST=redis-server
      - REDIS_SERVER_PORT=6379
    ports:
      - "3000:3000"
    depends_on:
      - redis-server
