apiVersion: v1
kind: Service
metadata:
  name: redis-server-service-cluster-ip
  namespace: fibonacci
spec:
  type: ClusterIP
  selector:
    fibonacci: redis-server
  ports:
    - port: 6379
      targetPort: 6379
