apiVersion: v1
kind: Service
metadata:
  name: postgres-server-service-cluster-ip
  namespace: fibonacci
spec:
  type: ClusterIP
  selector:
    fibonacci: postgres-server
  ports:
    - port: 5432
      targetPort: 5432
