version: "2" # version of docker compose

services:
  noobie-web-app:
    build: .
    image: noobie-web-app-image:latest
    container_name: noobie-web-app-container
    hostname: noobie-web-app
    restart: "no"
    environment:
      - APP_PORT=3000
    ports:
      - "3000:3000"
