apiVersion: v1
kind: Service
metadata:
  name: backend-service-cluster-ip
  namespace: fibonacci
spec:
  type: ClusterIP
  selector:
    fibonacci: backend
  ports:
    - port: 5000
      targetPort: 5000
